### ISSUE TITLE
Add `id` attribute to table

### ISSUE THREAD

**Issue by barnumbirr** [TheRenegadeCoder/SnakeMD#160]
Hi,

I'm currently using SnakeMD (not v2.0.0+, shame on me 🙈 ) to generate pages that include multiple HTML tables. To allow for the usage of libraries such as [datatables](https://datatables.net/), it would be helpful for SnakeMD to be able to create tables with different id attributes.

I could not find anything related to my issue in the documentation, is that a feature that could be added in the future?

Thanks.

**Comment by jrg94** [comment]
Great question! To my knowledge, there is no support for HTML-style `id` attributes in markdown. However, there might be a couple solutions for you. The first I can think of is wrapping the table in a `div`. You can mix HTML and Markdown to a certain extent, so it would be absurd to do something like:

```python
doc.add_raw('<div id="my-table">')
# add table
doc.add_raw('</div>')
```

I'm not familiar with datatables, so if the `id` attributes need to be on the table elements, you might need to convert the markdown to HTML first, insert your tags, and then render the document. Otherwise, you'll have to make the HTML yourself using something like `add_raw`.

**Comment by barnumbirr** [comment]
Unfortunately wrapping the table in a `div` isn't possible, as per the [Inline HTML](http://daringfireball.net/projects/markdown/syntax#html) section of the Markdown reference.

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style emphasis inside an HTML block.

According to the Mardown reference, this is explicitly allowed for span-level tags

> Unlike block-level HTML tags, Markdown syntax is processed within span-level tags

So I tried using

```
doc.add_raw('<span id="my-table">')
# add table
doc.add_raw('</span>')
```

However this will not wrap the table but create the span element inside a empty paragraph as follows

```
<p><span id="my-table"></span></p>
```

I found [this explanation](https://stackoverflow.com/questions/44172954/is-it-possible-to-have-a-table-in-the-center-in-a-github-gist-markdown/44273097#44273097) as to why this happens.

For the time being, I've resorted to prepending my table with a heading so that I can call datatables as follows:

```
new DataTable('h3#my-id+table', {
} );
```

**Comment by jrg94** [comment]
Okay, interesting! Thanks for the follow up. If you're able to key into the following element, you might be able to use the same div trick by putting it ahead of the table:

```python
doc.add_raw('<div id="my-table"></div>')
doc.add_table(...)
```

Regardless, looks like you have something working!
